train.py
In my first run, I had a 60 entry eval and did evals every 100 iterations, so I literally spent 60/160 iterations doing eval. I didn't realize this until it was too far in so I didn't want to abort. Hopefully this might give people the hint earlier on so they won't waste time.
=> qol: warn user when they are about to spend a lot of time evaluating vs training

train.py
If a user sets warmup_steps to 0 (as opposed to commenting it out), the trainer will crash with a division by zero due to `start_factor` param in
https://github.com/tdrussell/qlora-pipe/blob/6336bd448e5dcc61e2e069283b612505df75bb84/train.py#L552
This PR disregards 0 case.
=> fix: deal gracefully with warmup_steps=0

engine.py, train.py, utils.py
This adds a simplified log function to adopt the other time prefixed log messages, and updates the steps printer to include total steps, as well as an ETA in hours.
Also bonus encouraging completion message. Will drop if unnecessary, but the abrupt drop to prompt makes it not immediately  clear whether the thing keeled over or finished.
=> improve steps logging including adding an ETA

merge_lora.py
This may not be super useful today, but it will be once/if you use safetensors LoRA format, and it lets people use your magnificent merge script for LoRAs that were made using some other tool that outputs safetensors adapter_model.
=> merge_lora: detect and use safetensors lora when present

examples/config_7b.toml, saver.py, train.py
Two things in this:
* Move save logic out of the train.py file.
* Add a `keep_states` option which lets you set the number of states (model saves and checkpoint saves) to keep. It discards excess states right before saving each time.
This is a rather big diff so I understand if you're hesitant to merge.
I think it's overall a step in the right direction, but you may have a different idea for how to address this.
=> add old-state trimming and handle saving in new module

train.py
This adds a --resume_from_checkpoint flag to the command line args which overrides config specified value.
It also allows for configs where `resume_from_checkpoint` is not given, which would othewrise give a key error. See #11 which this PR supercedes.
=> feature: add --resume_from_checkpoint flag

saver.py, train.py
With model checkpoints being trimmed away, it is possible that one might auto-lose the best evaluating checkpoint in the current set up. This PR compares the eval loss to the best seen and saves a "best_loss" checkpoint that is overwritten each time a new best is achieved.
1. I'm not sure I am getting the loss for all evals now. I think I do, but it would be great to have this confirmed.
2. Is there a more elegant way to relay `pending_best_loss_save` than doing a file write and `os.path.exist` check in the process_step loop? My deepspeed knowledge is limited.
=> feature: track and hold onto best eval model

llama_pipe.py
I'm pretty sure `orig` is `lm_head` here, as indicated in the comment above.
I crashed on this when I was playing around with `model_type` other than the default. Using `lm_head` seems to do the trick.
=> bug-fix: use right varname in lm_head

train.py
Fixed `torch.log(1e-10 + losses)` to work with `model_weight_dtype` of `float16`.
`float16` has a minimum sub-normal value of approx `5.96e−8`, so changed to use `1e-8` and now the histogram shows up correctly when using `float16`.
=> Fixed "log_loss_hist" to work with float16

dataset_utils.py
For configurations where eval dataset is explicitly set, the `eval_size` is not used or set to `0`. In both of these cases, due to the if case regarding eval_size == 0 as `not True`, the code will fail to set the `val_set_size cfg` param, resulting in a crash in Axolotl code, which assumes it is a numeric non-None value.
The relevant code is in https://github.com/axolotl-ai-cloud/axolotl/blob/cd2d89f4672e90af45c6a632c75a624b6219c712/src/axolotl/utils/data/sft.py#L523-L525
```py
val_set_size = (
int(cfg.val_set_size) if cfg.val_set_size > 1 else float(cfg.val_set_size)
)
```
=> do not crash if eval_size is not set

examples/config.toml, train.py
It can be nice to have the final evaluation results after the training completes, as the last eval schedule may occur long before the final training step for higher eval steps. This enforces that an evaluation happens after the last step always, taking into account whether an eval happened already.
The flag is set to false in the example config, so people would have to explicitly turn it on to use it.
=> eval_after_last_step flag

train.py
Some issues that need addressing, so keeping as draft.
=> LoRA+ support

merge_lora.py
I very often find that a merge results in copying a stray gguf file and, for recent Mistral models, the consolidated.safetensors file is caught up in the mix as well.
This simply skips over the offending types (.gguf, .safetensors).
=> merge_lora: skip .gguf, .safetensors in copy stage

train.py
This adds a eta_min to the LR scheduler for CosineAnnealingLR. It is set along with the lr, e.g.
```toml
lr = 1e-6
lr_min = 1e-7
```
=> feature: minimum learning rate for cosine scheduler

train.py
The lr and lr_min should ideally be in the same place. This code moves the lr_min from the global config to inside [optimizer] to be with lr.
I actually didn't even realize I made the mistake until a training run silently ignored my lr_min and went down to 0.
=> Use optim_config for lr_min

llama_pipe.py
Fixes #30.
Both `LlamaForCausalLMPipe` and `Qwen2ForCausalLMPipe` should now detect the presence of:
```json
"tie_word_embeddings": true,
```
and if set true, pass `tie_weights='model.embed_tokens.weight'` to the `LmHeadPipe` call.
https://huggingface.co/unsloth/Llama-3.2-1B-Instruct/blob/main/config.json
https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/blob/main/config.json
=> Both `LlamaForCausalLMPipe` and `Qwen2ForCausalLMPipe` should detect `"tie_word_embeddings": true`

layers.py, train.py
This PR adds `hidden_norm_avg` and `hidden_norm_hist` metrics:
It uses the hidden-state before it is multiplied by `self.logit_scale`.
The reason this is useful is because all the Focal Loss variants tend to "cheat" (by shrinking the hidden states) after you scale `gamma` beyond a certain point.
This should let you monitor this effect and then use Focal Loss to increase the Entropy of the models' outputs only up to the point where the balance of shrinking the hidden states outweighs the increase in log-loss caused by the attention blocks all having their inputs from the residual-stream down-scaled.
You can see the effect of `gamma=1.1` for Focal Loss\* in the pink lines - this is a continuation of the model with the grey line, which was previously trained using stock Cross-Entropy loss on …
=> Add final hidden-state metrics

dataset_utils.py
This is a slightly improved version of `yield_sequences_from_token_batch`:
- Doesn't overwrite the first token of each sequence with the `BOS` token.
- Slightly less list slicing operations .
The logic for the `BOS` tokens is a little simpler too. AFAIK, the `"add_bos_token": true` option in `tokenizer_config.json` is actually often ignored and that's why you often see Jinga2 templates with `"template": "{{ bos_token }}...` in them even when `"add_bos_token": true`  is set.
---
This was actually just part of another branch where I tried all sorts to see if I could fix `load_raw_dataset` to work with very large files and/or lots of small files:
- I get an OOM error inside `dataset.set_format(type='torch')` when trying to pass it a single ~500MB text file (on a machine with 512GB of RAM!). …
=> Slightly improved version of `yield_sequences_from_token_batch`

examples/config.toml, saver.py
I never really liked that checkpoints and saves are not synced up, but I respect varied opinions. This PR adds a flag to the config called `checkpoint_on_save` which, if `true`, will ignore the `checkpoint_every_n_minutes` value and save the checkpoint along with the `step`, every time.
Potentially, it may be useful to add code that raises an exception if `checkpoint_on_save` is set and `checkpoint_every_n_minutes` is present so people don't get confused, but I personally don't think it's necessary.
~Draft as I haven't tested this (yet), due to an ongoing training run.~ Tested. Works as expected on my end.
=> feature: allow checkpoint save synchronized with step save

kernels/cross_entropy_loss.py, kernels/utils.py
Both AMD and NVIDIA gpus can launch at most 1024 threads per block.
Triton launches num_warp * device warp size threads.
All nvidia gpus have a warp size of 32 so you can launch at most 32 warps per block on those.
Some AMD gpus (GCN and CDNA) have a warp size of 64, others (RDNA) have a selectable warp size of 32 or 64, with 64 most often used by aco and llvm for game shaders and 32 being most often used by llvm in compute contexts.
We must thus limit the num_warp parameter to at most 16 on GCN and CDNA devices and on RDNA devices in warp64 mode. Unfortunately Triton dose not appear to expose this information (which is pretty silly, maybe i missed it) so as a workaround i have implemented checking the type of gpu and guessing the warp size based on that, this works fine for Nvidia gpus, …
=> Scale number of launched warps by device warp size to avoid block thread limits

kernels/utils.py
num_warps ends up as a float since https://github.com/tdrussell/qlora-pipe/pull/55 which is a problem in some cases, seams to be dependant on the model chosen, becasue triton can end up doing a bitwise operation with this value.
```
[rank1]: Traceback (most recent call last):
[rank1]:   File "scripts/qlora-pipe/train.py", line 676, in <module>
[rank1]:     metrics = model_engine.train_batch()
[rank1]:   File "scripts/qlora-pipe/engine.py", line 122, in train_batch
[rank1]:     self._exec_schedule(sched)
[rank1]:     ~~~~~~~~~~~~~~~~~~~^^^^^^^
[rank1]:   File "venv/lib/python3.13/site-packages/deepspeed/runtime/pipe/engine.py", line 1422, in _exec_schedule
[rank1]:     self._exec_instr(**cmd.kwargs)
[rank1]:     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
[rank1]:   File "scripts/qlora-pipe/engine.py", …
```
=> Fix num_warps being ending up as a float

utils/dataset_utils.py
Just ran into this assert causing problems when passing in pre-formatted data to `yield_sequences_from_token_batch()`.
I don't think there is any good reason for it to be an assert?
=> Fixed `assert tokens[-1] != tokenizer.eos_token_id` in `yield_sequences_from_token_batch()`
